### ISSUE TITLE
installing over signalk BLE plugin

### ISSUE THREAD

**Issue by gregsyoung** [j9brown/victron-ble#6]
hi jeff
been following this for some time, and was hopeful the various updates would be merged into the original plugin, and hence enable simple updating, however this has been pending now for some time ..

am i correct that i need to uninstall the (keshadev) plugin from signalk, and then manually 
add your version using pip.
this would then appear as normal in signalk, but have all the various updates (inc smart battery support) .

im not very experienced with github merging et al .. hence just validating my understanding

**Comment by j9brown** [comment]
Sorry I'm not familiar with signalk.  My guess is that just updating the version of this library will not be enough to add new features to signalk.  Each new device type needs to be handled by the client application code.

**Comment by gregsyoung** [comment]
noted thx… i believe the changes will hopefully get integrated in due course into victron-ble, and subsequently into the signalk plugin that relies on above.

**Comment by j9brown** [comment]
Good news!  The upstream maintainer of this library has merged in my changes so you may well be one step closer to having these features available in signalk someday.

**Comment by gregsyoung** [comment]
indeed v good news.
and thank you for your efforts on thus.
much appreciated
